name: Trigger auto deployment for container-app-av5qhspba3g62

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-av5qhspba3g62-AutoDeployTrigger-9e526404-f857-4c04-bcaf-4af76141ca50.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPAV5QHSPBA3G62_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPAV5QHSPBA3G62_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPAV5QHSPBA3G62_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPAV5QHSPBA3G62_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPAV5QHSPBA3G62_REGISTRY_PASSWORD }}
          containerAppName: container-app-av5qhspba3g62
          resourceGroup: flaskbasic984d8d21
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


